### ISSUE TITLE
Show the posts as per the most recent date

### ISSUE THREAD

**Issue by ghost** [jxson/haiku#13]
Write now its been done like in blog.html

<% site.content.blog.posts.pages.sort_by(&:published).reverse[0..7].each do |post|  %>
## Blog.html

layout: all-posts
title: Blog
## published: 2009-01-01

<div class="push container"> 
  <h1 class="left uppercase">Latest Posts</h1> 
  <div class="clear"></div> 

  <div class="two-boxes"> 

```
<% site.content.blog.posts.pages.sort_by(&:published).reverse[0..7].each do |post| %>
  <div class="post box">
    <div class="box-content"> 
      <h4><a href='<%= post.url %>'>{{title}}</a></h4>
      <p class='left date'>{{published}}></p>
      <div class='clear'></div>    
      <p>{{excerpt}}</p>
      <div class="post-footer"> 
        <a href="<%= post.url %>#disqus_thread" class="comment-count" data-disqus-identifier="<%= post.name %>"></a> 
        <a href="<%= post.url %>" class="right">Continue reading &raquo;</a> 
        <div class="clear"><!-- --></div> 
      </div><!-- /.post-footer -->
    </div><!-- /.box -->
  </div><!-- /.post box -->
<% end %>
```

  </div> 
</div> 

{{>blog-navigation}}

**Comment by jxson** [comment]
I have this partially worked out in the sort-by-published branch, can you check it out and run it against the site to see that the  order is correct?

I am still working on the bit to add the limit. Most likely this will come when I make changes to the way the config works since you will be able to add your own arbitrary helpers

**Comment by jxson** [comment]
@nratan I am pretty sure I have this working now, you can add something like this to a config file:

```
module.exports = {
  attributes: {
    recent: function(){
      var site = this;

      return site.collections.posts.pages.slice(0, 8);
    }
  }
};
```

And then you can loop through those posts with something like this:

```
{{#site}}
  {{#recent}}
    <div class="post box">
      <div class="box-content">
        <h4><a href='{{ url }}'>{{title}}</a></h4>

        <p class='left date'>{{ published }}></p>

        <div class='clear'></div>

        <p>{{ excerpt }}</p>

        <div class="post-footer">
          <a href="{{ url }}#disqus_thread"
            class="comment-count"
            data-disqus-identifier="{{ name }}">
          </a>

          <a href="{{ url }}" class="right">Continue reading &raquo;</a>

          <div class="clear"><!-- --></div>
        </div><!-- /.post-footer -->
      </div><!-- /.box -->
    </div><!-- /.post box -->
  {{/recent}}
{{/site}}
```

The only catch is you have to tell haiku where to look for the config:

```
haiku server --config path/to/config.js
```

Let me know how it goes, if it's working feel free to close this issue...

**Comment by ghost** [comment]
This issue has been tested for all the pages which were using this format and it ran successfully. So I am closing this issue now.
